--create table for suppliers
CREATE table P1 (
SUPPLIER_NAME VARCHAR2(2000), 
SUPP_CONTACT_NAME VARCHAR2(2000),
SUPP_ADDRESS VARCHAR2(2000), 
SUPP_CONTACT_NUMBER1 NUMBER(38),
SUPP_CONTACT_NUMBER2 NUMBER(38),
SUPP_EMAIL VARCHAR2(2000),
PRIMARY KEY(SUPPLIER_NAME)
);

--create table for invoices
CREATE TABLE P2(
ORDER_REF VARCHAR2(2000),
INVOICE_REFERENCE VARCHAR2(2000),
ORDER_DESCRIPTION VARCHAR2(2000),
INVOICE_DATE DATE,
INVOICE_STATUS VARCHAR2(2000),
INVOICE_AMOUNT NUMBER(38),
INVOICE_HOLD_REASON VARCHAR2(2000),
INVOICE_DESCRIPTION VARCHAR2(2000),
PRIMARY KEY(ORDER_REF, INVOICE_REFERENCE, ORDER_DESCRIPTION)
);

--create table for orders
CREATE TABLE P3(
ORDER_REF VARCHAR2(2000),
INVOICE_REFERENCE VARCHAR2(2000),
SUPPLIER_NAME VARCHAR2(2000),
ORDER_DESCRIPTION VARCHAR2(2000),
ORDER_DATE DATE,
ORDER_TOTAL_AMOUNT NUMBER(38),
ORDER_STATUS VARCHAR2(2000),
ORDER_LINE_AMOUNT NUMBER(38),
PRIMARY KEY(ORDER_REF, INVOICE_REFERENCE, ORDER_DESCRIPTION)
);