DECLARE
 v_query_3 VARCHAR2(2000 CHAR);
BEGIN
    v_query_3 := 'INSERT INTO P2 (ORDER_REF, INVOICE_REFERENCE, ORDER_DESCRIPTION, INVOICE_DATE, INVOICE_STATUS, INVOICE_AMOUNT, INVOICE_HOLD_REASON, INVOICE_DESCRIPTION)
select 
ORDER_REF,
	INVOICE_REFERENCE 	,
  REPLACE(ORDER_DESCRIPTION, ''"'', '' inches'') AS ORDER_DESCRIPTION,
	to_date(INVOICE_DATE,''DD-MM-YYYY'') as INVOICE_DATE, 
	INVOICE_STATUS,
	TO_NUMBER(replace(replace(replace(replace(upper(INVOICE_AMOUNT),''O'', ''0''),''S'',''5''), ''I'', ''1''), '','', '''')) as INVOICE_AMOUNT,
  INVOICE_HOLD_REASON,
  REPLACE(INVOICE_DESCRIPTION, ''#'', '''')
  from practice_table
  where UPPER(ORDER_STATUS) in (''RECEIVED'')';
    
    EXECUTE IMMEDIATE v_query_3;
   
END;
/