DECLARE
 v_query_3 VARCHAR2(2000 CHAR);
BEGIN
    v_query_3 := 'INSERT INTO P3 (ORDER_REF, INVOICE_REFERENCE,SUPPLIER_NAME, ORDER_DESCRIPTION, ORDER_DATE, ORDER_TOTAL_AMOUNT, ORDER_STATUS, ORDER_LINE_AMOUNT)
select distinct
	ORDER_REF,
  NVL(INVOICE_REFERENCE,''-''),
  SUPPLIER_NAME,
  REPLACE(ORDER_DESCRIPTION, ''"'', '' inches''),
	to_date(ORDER_DATE,''DD-MM-YYYY'') as ORDER_DATE,
	TO_NUMBER(REPLACE(ORDER_TOTAL_AMOUNT,'','','''||''' )) as ORDER_TOTAL_AMOUNT,
 ORDER_STATUS,
  TO_NUMBER(replace(replace(replace(replace(upper(ORDER_LINE_AMOUNT),''O'', ''0''),''S'',''5''), ''I'', ''1''), '','', '''||''')) as ORDER_LINE_AMOUNT
  from PRACTICE_TABLE';
    
    EXECUTE IMMEDIATE v_query_3;
   
END;
/